# Generated by Django 5.2.5 on 2025-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В обробці'), ('confirmed', 'Підтверджено'), ('canceled', 'Скасовано')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='house',
            name='people_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість людей'),
        ),
    ]
