# Generated by Django 5.2.5 on 2025-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status_house_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коментар:'),
        ),
        migrations.AlterField(
            model_name='house',
            name='people_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість людей:'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість кімнат:'),
        ),
    ]
